"""Markdown export for generated notes.

Produces a well-formatted Markdown document with:
- Title and summary
- Sections with key points as bullet lists
- Timestamps as a table
- Action items as a checklist
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from notetaker.models import GeneratedOutput, VideoMetadata
from notetaker.utils.logging import get_logger

logger = get_logger("export.markdown")


def generate_markdown(
    output: GeneratedOutput,
    metadata: Optional[VideoMetadata] = None,
) -> str:
    """Generate a Markdown string from generated output.

    Args:
        output: The generated notes, timestamps, and action items.
        metadata: Optional video metadata for header info.

    Returns:
        Formatted Markdown string.
    """
    lines: list[str] = []
    notes = output.structured_notes

    # Title
    lines.append(f"# {notes.title}")
    lines.append("")

    # Metadata block
    if metadata:
        lines.append("> **Video Notes** generated by Deep-Dive Video Note Taker")
        if metadata.source_url:
            lines.append(f"> Source: {metadata.source_url}")
        duration_min = metadata.duration_seconds / 60
        lines.append(f"> Duration: {duration_min:.1f} minutes")
        lines.append(f"> Processed: {metadata.processing_date[:10]}")
        lines.append(f"> Models: Whisper {metadata.whisper_model} | {metadata.ollama_model}")
        lines.append("")

    # Summary
    if notes.summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(notes.summary)
        lines.append("")

    # Sections
    if notes.sections:
        lines.append("## Notes")
        lines.append("")
        for section in notes.sections:
            lines.append(f"### {section.heading}")
            lines.append("")
            for point in section.key_points:
                lines.append(f"- {point}")
            lines.append("")

    # Timestamps
    if output.timestamps:
        lines.append("## Key Timestamps")
        lines.append("")
        lines.append("| Time | Description |")
        lines.append("|------|-------------|")
        for ts in output.timestamps:
            lines.append(f"| {ts.time} | {ts.label} |")
        lines.append("")

    # Action Items
    if output.action_items:
        lines.append("## Action Items")
        lines.append("")
        for item in output.action_items:
            assignee = f" *(@{item.assignee})*" if item.assignee else ""
            ts = f" `[{item.timestamp}]`" if item.timestamp else ""
            lines.append(f"- [ ] {item.action}{assignee}{ts}")
        lines.append("")

    return "\n".join(lines)


def export_markdown(
    output: GeneratedOutput,
    metadata: Optional[VideoMetadata],
    path: Path,
) -> None:
    """Export notes as a Markdown file.

    Args:
        output: Generated notes.
        metadata: Video metadata.
        path: Output file path.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    content = generate_markdown(output, metadata)

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Markdown exported: {path}")
